# Generated by Django 5.0.14 on 2026-03-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="projects/"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="client_avatar",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
    ]
