# Generated by Django 5.0.14 on 2026-08-21 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_alter_blogpost_featured_image_alter_project_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="updated_date",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="clients/"),
        ),
        migrations.AlterField(
            model_name="skill",
            name="proficiency",
            field=models.PositiveIntegerField(
                default=50,
                help_text="Proficiency percentage (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
